services:
  - type: web
    name: ecotrack
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn EcoTrack.wsgi:application"
    envVars:
      - key: RENDER
        value: "true"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "csit327-g5-ecotrack.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://csit327-g5-ecotrack.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromSecret: postgresql://postgres.dquruduxedbdizlkfmoa:NMTsGkQF9Qob6K3D@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require